services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: speedyshop-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123"
    ports:
      - "1433:1433"
    volumes:
      - speedyshop-sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_strong_password123 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.2
    container_name: speedyshop-aspire-dashboard
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"

volumes:
  speedyshop-sql-data: